### ISSUE TITLE
Use Polyline dependency

### ISSUE THREAD

**Issue by tmcw** [mapbox/MapboxStatic.swift#11]
Just like MapboxDirections.swift, we should depend on the Polyline lib

**Comment by 1ec5** [comment]
This will depend on restructuring the project to produce a dynamic framework (#2), much as we've done for MapboxDirections.swift and MapboxGeocoder.swift.

**Comment by 1ec5** [comment]
This will be unblocked once #16 lands.

**Comment by tmcw** [comment]
#16 landed, can I grab?

**Comment by 1ec5** [comment]
Be my guest!

**Comment by tmcw** [comment]
👍 waiting on https://github.com/raphaelmor/Polyline/pull/27

**Comment by 1ec5** [comment]
raphaelmor/Polyline#27 is merged and Polyline’s podspec has been bumped to 3.1.0, but CocoaPods’ central repository hasn’t been updated yet. Since the polyline functionality in this repository already works, we should wait until CocoaPods gets updated. Otherwise, downstream users will have to include a second line in their podfile to override the version that CocoaPods resolves the pod to.

**Comment by 1ec5** [comment]
Polyline has been updated with support for all the platforms this library supports.

**Comment by incanus** [comment]
Counterargument: polyline encoding/decoding is so small and lightweight, we might be able to get away with just sourcing this internally. For example here is a port of our JS version that I did recently: https://gist.github.com/incanus/47737ead1b92ff12095070ca11c493d0

**Comment by tmcw** [comment]
I'm happy to vendor an existing Polyline lib, but hesitant to write one ourselves that doesn't have a separate bug tracker. The basic polyline algorithm looks simple, but in [mapbox/polyline](https://github.com/mapbox/polyline/pulls?q=is%3Apr+is%3Aclosed) we've learned about a sneaky class of errors around the particular behavior of number handling in JavaScript - I'd expect similar tiny but significant problems from any new implementation in any language, and want to make sure we have a place to fix them once and for all if/when we find them.

**Comment by 1ec5** [comment]
@incanus, are there any substantive differences between your implementation and the one in the Polyline pod?

**Comment by incanus** [comment]
No, my thinking was about brevity and about less dependencies (even if our own, external dependency, it’s still easier IMHO) but I don’t feel strongly. I would want tests, yes, to exercise what I have written better. You two know better than I if dependencies have been enough of a problem or not.

**Comment by 1ec5** [comment]
Now that this project uses Carthage for dependency management and is written in Swift 3, it should be a lot more straightforward for this project to depend on Polyline v4.0 the way MapboxDirections.swift does.

**Comment by 1ec5** [comment]
#53 introduces a dependency on Polyline. Of interest, one of the test fixtures had to be changed because of an encoding difference, but the classic Static API output remained unchanged.

**Comment by 1ec5** [comment]
#53 needs some conflict resolution, but we’ll close this issue once that PR lands.
