### ISSUE TITLE
Use guards instead of assertions for API limits

### ISSUE THREAD

**Issue by tmcw** [mapbox/MapboxStatic.swift#12]
https://github.com/mapbox/MapboxStatic.swift/blob/master/MapboxStatic.swift#L111-L115

I don't think these make sense as traditional assertions - for people who are requesting with variable numbers they won't run at the right time.

**Comment by 1ec5** [comment]
I think these are valid conditions to raise exceptions for. It’s the responsibility of client code to ensure that whatever size they pass in avoids this limit. The alternative is to return a smaller image or no image at all, but that could be subtle and unexpected, with no opportunity to communicate the reason for the discrepancy. These limits should be properly communicated in documentation so clients are aware of their responsibility: #13.
