### ISSUE TITLE
Migrate to Swift 3

### ISSUE THREAD

**Issue by alexanderniebuhr** [mapbox/MapboxStatic.swift#46]
Hello,

i really need to work with the MapboxStatic.framework

When is do you plan the full support release for swift 3

Kind Regards
Alex

**Comment by xiangyu-sun** [comment]
waiting for that too

**Comment by 1ec5** [comment]
A migration to Swift is underway in #50. Please give it a try and let me know if you see anything amiss. Thank you for your patience.
