### ISSUE TITLE
consider rename

### ISSUE THREAD

**Issue by incanus** [mapbox/MapboxStatic.swift#6]
The more I think about this library, the more I think it really fills a neat niche in iOS tools, since MapKit gives you nothing even close to this. That said, `MapboxStatic` is not a welcoming name, even if it is in line with our backend service. 

Something like `MapboxImage` or `MapImage` could be better here, since it speaks to the produced result: a `UIImage` of a map.

**Comment by tmcw** [comment]
I think this name is great, and lines up with MapboxDirections MapboxGeocoder et. al!
