### ISSUE TITLE
Path: always draw a polygon instead of a polyline

### ISSUE THREAD

**Issue by matvdg** [mapbox/MapboxStatic.swift#62]
Hi,
I want to use the class Path to draw a polyline (my start point differs from my end point) and it doesn't work anymore, it's always a closes polygone being drawn. It's pretty weird because in your demo it works fine (polyline) in my playground and I copy the exact same code in my project, it's a polygon...

**Comment by 1ec5** [comment]
This was fixed in #58. We’ll publish a release with the fix as soon as #63 lands. In the meantime, you can use the master branch, which includes the fix.
