### ISSUE TITLE
more unit test coverage

### ISSUE THREAD

**Issue by incanus** [mapbox/MapboxStatic.swift#7]
Lower priority for now since we've determined what we need to from writing the initial tests, but Xcode 7 shows some lack of coverage: 

![screen shot 2015-10-29 at 10 30 46 am](https://cloud.githubusercontent.com/assets/17722/10826703/3d5905b8-7e28-11e5-930d-b64b83c2fcdb.png)

We should be exercising things like color-to-hex and vice-versa.

**Comment by 1ec5** [comment]
Test coverage has improved significantly since this issue was written. As of https://github.com/mapbox/MapboxStatic.swift/pull/54#issuecomment-284893753, we’re at 76.97%. As far as I can tell, most of the improvement has come from streamlining the library rather than from adding more tests.
