### ISSUE TITLE
I need some help, this is not an issue

### ISSUE THREAD

**Issue by jbarros35** [mapbox/MapboxStatic.swift#93]
I don't know who else to ask help so I'm trying here sorry but this is how works...

I'm using Mapbox for tracking device and I need to display clustered positions like we have on default Apple maps. I'm reading this sample but this is totally fair away my reality here.
https://docs.mapbox.com/ios/maps/examples/clustering/

I get my positions from a service, not a geoJSON file, so that approach simple doesn't work for us. I need to display clustered when zooming out because we have a lot of positions but we still need do declutter it when tap, as I said, exactly like Apple Maps does.

Can you provide me samples for doing it? I just can't find anyone else that understand the documentation right now.

**Comment by julianrex** [comment]
Marking as answered in https://github.com/mapbox/mapbox-gl-native/issues/14584.
