### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxStatic.swift#95]
Add a Package.swift file so that [Swift Package Manager](https://swift.org/package-manager/) can incorporate this library into a project.

/ref mapbox/MapboxDirections.swift#234 mapbox/MapboxGeocoder.swift#132
/cc @mapbox/maps-ios @frederoni

**Comment by EmDee** [comment]
@frederoni Have you tried this with Xcode 11? I'm getting an error when trying to integrate your project:
![grafik](https://user-images.githubusercontent.com/717205/63700741-d1284a80-c823-11e9-89b9-aae63f443072.png)

**Comment by frederoni** [comment]
@EmDee The latest version 0.10.0, does not yet have a Package.swift file. You'll have to select Branch: master on the second screen in Xcode 11 until we make a new release.
